# Generated by Django 4.2.11 on 2024-05-06 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_app', '0002_answers1_answers2_answers_q2'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='user_cookies',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers1',
            name='user_cookies',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers2',
            name='user_cookies',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
